---
name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test-default:
    uses: ./.github/workflows/test-default.yml
    needs: [lint]
  test-ipv6:
    uses: ./.github/workflows/test-ipv6.yml
    needs: [lint, test-default]
  test-single-node:
    uses: ./.github/workflows/test-single-node.yml
    needs: [lint, test-default, test-ipv6]
