---
name: Test Default
on:
  workflow_call:
jobs:
  steps:
    - name: Default
      uses: .github/workflows/molecule-template.yml
  molecule:
    strategy:
      matrix:
        scenario:
          - default
