---
name: Test Default
on:
  workflow_call:
jobs:
  molecule:
    name: Molecule
    runs-on: macos-12
    strategy:
      matrix:
        scenario:
          - default
      fail-fast: false
    env:
      PYTHON_VERSION: "3.11"
runs:
  steps:
    - uses: ./.github/workflows/molecule-template.yml
