---
name: Test Default
on:
  workflow_call:
jobs:
  molecule:
    name: Molecule
    runs-on: macos-12
    strategy:
      matrix:
        scenario:
          - default
      fail-fast: false
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v3 2.5.0
      - uses: "./.github/workflows/molecule-template.yml"
