---
name: Test Single Node
on:
  workflow_call:
jobs:
  molecule:
    name: Molecule
    runs-on: macos-12
    strategy:
      matrix:
        scenario:
          - single_node
      fail-fast: false
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: ./.github/workflows/molecule-template.yml
